version: '2'
services:
    problems-db:
        container_name: digital-model-problems-database
        build:
            context: ./insert_to_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: problems
    problems-db-create:
        container_name: digital-model-problems-database-init
        build:
            context: ./insert_to_db
            dockerfile: dockerfile-createdb
        command: python /insert_to_db.py --host=problems-db --csv_path=/csv/problems_export_2020-05-27.csv
        depends_on:
            - problems-db
    problems-api:
        container_name: digital-model-problems-api
        image: java
        build:
            context: ./problemapi
        command: java -jar /app.jar --db_string="jdbc:postgresql://problems-db:5432/problems"
        ports:
            - 8081:80
        depends_on:
            - problems-db